# Generated by Django 5.1.6 on 2025-06-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('monthly_fee', models.PositiveIntegerField()),
                ('total_sessions', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('GYM', 'gym'), ('YOGA', 'yoga'), ('CROSSFIT', 'crossfit'), ('PILATES', 'pilates'), ('SWIMMING', 'swimming')], default='GYM', max_length=50)),
                ('facilities', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('established_date', models.DateField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
